CREATE TABLE if not exists hits
(
    id bigint generated by default as identity primary key not null,
    app varchar(30),
    uri varchar(1024) not null,
    ip varchar(16) not null,
    timestamp timestamp without time zone not null
);
