server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  application:
    name: "ewm-main-service"

---
spring:
  config:
    activate:
      on-profile: ci, test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm
    username: root
    password: root
  application:
    name: "ewm-main-service"
